% Produced by CVXGEN, 2012-03-15 08:24:15 -0700.
% CVXGEN is Copyright (C) 2006-2011 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2011 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.

function [vars, status] = cvxsolve(params, settings)

B_min = params.B_min;
Delta = params.Delta;
K = params.K;
h_mns = params.h_mns;
h_pls = params.h_pls;

cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable F(44, 1);

  minimize(sum(square(F)));
  subject to
    sum(max(-(Delta - K*F), 0)) <= B_min;
    h_mns <= F;
    F <= h_pls;
cvx_end

vars.F = F;
status.cvx_status = cvx_status;

% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
